2025-07-25 08:09:43,984 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for internship.localhost
2025-07-25 08:09:44,029 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for internship.localhost
2025-07-25 08:09:44,048 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for internship.localhost
2025-07-25 08:09:44,051 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for internship.localhost
2025-07-25 08:09:44,085 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for internship.localhost
2025-07-25 08:09:44,095 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for internship.localhost
2025-07-25 08:09:44,099 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-07-25 08:09:44,107 ERROR scheduler Skipped queueing frappe.core.doctype.log_settings.log_settings.run_log_clean_up because it was found in queue for internship.localhost
2025-07-25 08:09:44,128 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for internship.localhost
2025-07-30 09:59:05,083 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for internship.localhost
2025-07-30 09:59:05,179 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.remove_unverified_record because it was found in queue for internship.localhost
2025-07-30 09:59:05,203 ERROR scheduler Skipped queueing frappe.core.doctype.log_settings.log_settings.run_log_clean_up because it was found in queue for internship.localhost
2025-07-30 09:59:05,277 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for internship.localhost
2025-07-30 09:59:05,332 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-07-30 09:59:05,372 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for internship.localhost
2025-07-30 09:59:05,385 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for internship.localhost
2025-07-30 09:59:05,457 ERROR scheduler Skipped queueing frappe.automation.doctype.auto_repeat.auto_repeat.make_auto_repeat_entry because it was found in queue for internship.localhost
2025-07-30 09:59:05,512 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for internship.localhost
2025-07-30 09:59:05,787 ERROR scheduler Skipped queueing frappe.social.doctype.energy_point_settings.energy_point_settings.allocate_review_points because it was found in queue for internship.localhost
2025-07-30 09:59:05,981 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_drive.google_drive.daily_backup because it was found in queue for internship.localhost
2025-07-30 09:59:06,213 ERROR scheduler Skipped queueing frappe.sessions.clear_expired_sessions because it was found in queue for internship.localhost
2025-07-30 09:59:06,283 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for internship.localhost
2025-07-30 09:59:06,319 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for internship.localhost
2025-07-30 09:59:06,736 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_contacts.google_contacts.sync because it was found in queue for internship.localhost
2025-07-30 09:59:07,117 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for internship.localhost
2025-07-30 09:59:07,143 ERROR scheduler Skipped queueing frappe.desk.notifications.clear_notifications because it was found in queue for internship.localhost
2025-07-30 09:59:07,160 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for internship.localhost
2025-07-30 10:00:12,650 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-07-30 10:00:12,718 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for internship.localhost
2025-07-30 12:08:31,675 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1463, in get_connection
    if connection.can_read():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 861, in can_read
    return self._parser.can_read(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 444, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 455, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1467, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:09:33,899 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:10:38,833 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:11:43,466 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:12:48,322 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:13:53,584 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:14:56,490 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:16:02,035 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:17:07,508 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:18:12,551 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:19:17,563 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:20:22,449 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:21:26,903 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-07-30 12:22:29,293 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 699, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 700, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1002, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 990, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 102, in enqueue_events_for_site
    enqueue_events(site=site)
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 122, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 95, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 568, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 573, in get_job_status
    job = get_job(job_id)
          ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 580, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 989, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4887, in hgetall
    return self.execute_command("HGETALL", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1457, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 705, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11003. Connection refused.
2025-08-01 08:37:20,938 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for internship.localhost
2025-08-01 08:37:21,109 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for internship.localhost
2025-08-01 08:37:21,426 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for internship.localhost
2025-08-01 09:33:12,537 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:34:15,673 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:35:21,658 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:36:27,695 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:37:33,601 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:38:39,003 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:39:44,443 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
2025-08-01 09:40:50,539 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for internship.localhost
